environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

shallow_clone: true

build_script:
  - gradlew clean check jacocoReport coveralls --stacktrace

test: off

notifications:
  - provider: Slack
    auth_token:
      secure: gWer52s7aL9Ekq/cMndHcqPy6cBA+hfslSWB39Stech28w5pZeWX1agpKHTTqyWr
    channel: ci
